### ISSUE TITLE
NameError: name 'Embedded' is not defined

### ISSUE THREAD

**Issue by k4n4n** [claroty/enip-stack-detector#1]
hello,

I am trying to use enip_stack_detector.py, but when I run it, I get this error:

![image](https://user-images.githubusercontent.com/43685859/195667895-e599aca3-af98-4b27-96be-c8f3f1c6b1b4.png)

Could you tell me what I should do?

Thanks!

Regards,

**Comment by SharonBrizinov** [comment]
please use python2 with `construct==2.9.45`. 
To quickly install `construct==2.9.45` please use: `pip2 -m install construct==2.9.45 --user`
